<?php
require 'autoload.php';
loader::registerAutoload();
$cart = new \Shop\Order\Cart();
$car = new \Shop\Products\Car('BMW', 1500000, 13);
//print_r ($car);
$book = new \Shop\Products\Book('littele prince', 43, 25);
$cart->AddProduct($car);
$cart->AddProduct($book);
echo $cart->PrintCart();
$cart->AddProduct($book);
echo $cart->PrintCart();
$cart->DelProduct($book->GetId());
echo $cart->PrintCart();
$book2 = new \Shop\Products\Book('Red Mars', 400, 10);
$cart->AddProduct($book2);
echo $cart->PrintCart();
$cart->ChangeQuantity($book2->GetId(), 40);
echo $cart->PrintCart();
\Shop\Order\Order::Save($cart, 'test@mail.ru');
